In [1]:
# 0. 필요한 모듈 임포트
# %config Completer.use_jedi = False

import numpy as np
import pandas as pd

In [2]:
# numpy 임의성
np.random.seed(42)

In [3]:
# 1. 데이터셋 가지고 오기
dataset = pd.read_csv('./DataSet/MNIST_preprocessed.csv', sep=',', header=None).values
dataset.shape

(300, 794)

In [4]:
# 입력, 목표 변수 데이터 셋 나누기
# 0 ~ 783 : MNIST dataset
X = dataset[:, 0:784]
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [5]:
# 784 ~ 793 : MNIST 데이터의 목표변수를 One hot encoding한 결과
Y = dataset[:, 784:]
Y

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
# training, testing 데이터 셋 나누기
X_train, X_test = X[0:250,], X[250:,]
Y_train, Y_test = Y[0:250,], Y[250:,]
X_train[0].shape

(784,)

In [7]:
# 시그모이드 함수 정의
def sigmoid(x):
    """시그모이드 함수"""
    return 1/(1 + np.exp(-x))

In [8]:
# 신경망의 가중치와 편향을 초기화해주는 함수
def initialize_parameters(neurons_per_layer):
    L = len(neurons_per_layer) - 1 # 층 개수 저장
    parameters = {}
    
    # 1층부터 L층까지 돌면서 가중치와 편향 초기화
    for l in range(1,L+1):
        
        # l층 가중치 행렬의 차원은 (l층 뉴런개수)x(l-1층 뉴런의 개수)
        # l층 편향벡터의 길이는 l
        parameters['W' + str(l)] = np.random.randn(neurons_per_layer[l],neurons_per_layer[l-1])/np.sqrt(neurons_per_layer[l])
        parameters['b' + str(l)] = np.random.randn(neurons_per_layer[l])/np.sqrt(neurons_per_layer[l])
        
    return parameters

# # 테스트코드
# neurons_per_layer = [10, 5, 5, 3]
# parameters = initialize_parameters(neurons_per_layer)
# print("parameter : \n {}\n\n".format(parameters))
# print("lenth of parameter : {}".format(len(parameters)))

In [9]:
# 순전파 Forward propergate 함수 정의
def feed_forward(x, parameters):
    """순전파 함수"""
    cache = {'a0': x}  # 0 번째 층 출력 저장
    L = len(parameters) // 2  # 층 수 저장 --> 파라미터에 whigt, bias있으니까 2로 나눔
    
    for l in range(1, L+1):
        # 전 층 뉴런의 출력, 현재 층 뉴런들의 가중치, 편향 데이터를 가지고 온다 (여기에 코드를 작성하세요)
        a_prev = cache['a' + str(l-1)]
        W = parameters['W'+ str(l)]
        b = parameters['b'+ str(l)]
        
        # 가지고 온 데이터로 z와 a를 계산한다. (여기에 코드를 작성하세요)
        z = W @ a_prev + b
        a = sigmoid(z)

        # 결과 값을 캐시에 저장한다.
        cache['z' + str(l)] = z
        cache['a' + str(l)] = a
                
    return a, cache

# 테스트 코드
neurons_per_layer = [784, 128, 64, 10]
parameters = initialize_parameters(neurons_per_layer)
feed_forward(X_train[0], parameters)[0]

array([0.39847399, 0.63077823, 0.79833093, 0.9305652 , 0.67941177,
       0.67579947, 0.05318345, 0.37468731, 0.12677545, 0.64191774])